/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 hero.gltf --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default  function Hero(props) {
  const { nodes, materials } = useGLTF('/hero-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[1.27, -2.36, -1.63]} rotation={[-0.13, -0.3, 0.47]}>
        <mesh geometry={nodes.Plane008_1.geometry} material={materials.Rosa} />
        <mesh geometry={nodes.Plane008_2.geometry} material={materials.Luz} />
        <mesh geometry={nodes.Plane008_3.geometry} material={materials['Rosa escuro']} />
        <mesh geometry={nodes.Plane008_4.geometry} material={materials['Material.017']} />
        <mesh geometry={nodes.Plane008_5.geometry} material={materials['Rosa.001']} />
        <mesh geometry={nodes.Plane008_6.geometry} material={materials['Verde escuro']} />
        <mesh geometry={nodes.Plane008_7.geometry} material={materials['Material.015']} />
        <mesh geometry={nodes.Plane008_8.geometry} material={materials['Material.014']} />
        <mesh geometry={nodes.Plane008_9.geometry} material={materials['Material.016']} />
        <mesh geometry={nodes.Plane008_10.geometry} material={materials['Material.025']} />
        <mesh geometry={nodes.Plane008_11.geometry} material={materials['Material.028']} />
        <mesh geometry={nodes.Plane008_12.geometry} material={materials['Material.029']} />
        <mesh geometry={nodes.Plane008_13.geometry} material={materials['Material.030']} />
      </group>
      <group position={[-0.27, -0.02, -0.12]} rotation={[-0.13, -0.3, 0.47]}>
        <mesh geometry={nodes.Plane009_1.geometry} material={materials['Preto.001']} />
        <mesh geometry={nodes.Plane009_2.geometry} material={materials.Luz} />
        <mesh geometry={nodes.Plane009_3.geometry} material={materials['Material.012']} />
        <mesh geometry={nodes.Plane009_4.geometry} material={materials['Preto escuro']} />
      </group>
      <group position={[-0.96, 0.7, 1.59]} rotation={[-0.13, -0.3, 0.47]}>
        <mesh geometry={nodes.Plane011_1.geometry} material={materials.Rosa} />
        <mesh geometry={nodes.Plane011_2.geometry} material={materials.Luz} />
        <mesh geometry={nodes.Plane011_3.geometry} material={materials['Rosa escuro']} />
        <mesh geometry={nodes.Plane011_4.geometry} material={materials['Material.008']} />
        <mesh geometry={nodes.Plane011_5.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Plane011_6.geometry} material={materials['Material.010']} />
      </group>
      <group position={[-0.27, -0.03, -0.12]} rotation={[-0.13, -0.3, 0.47]}>
        <mesh geometry={nodes.Plane012.geometry} material={materials.Rosa} />
        <mesh geometry={nodes.Plane012_1.geometry} material={materials.Luz} />
        <mesh geometry={nodes.Plane012_2.geometry} material={materials['Rosa escuro']} />
      </group>
      <group position={[0.37, -0.42, -2.57]} rotation={[-0.13, -0.3, 0.47]}>
        <mesh geometry={nodes.Plane016.geometry} material={materials.Preto} />
        <mesh geometry={nodes.Plane016_1.geometry} material={materials.Luz} />
        <mesh geometry={nodes.Plane016_2.geometry} material={materials.Rosa} />
        <mesh geometry={nodes.Plane016_3.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Plane016_4.geometry} material={materials['Rosa escuro']} />
      </group>
      <group position={[0.81, -1.47, -1.76]} rotation={[-0.13, -0.3, 0.47]}>
        <mesh geometry={nodes.Text_1.geometry} material={materials['Preto.001']} />
        <mesh geometry={nodes.Text_2.geometry} material={materials.Rosa} />
        <mesh geometry={nodes.Text_3.geometry} material={materials.Luz} />
        <mesh geometry={nodes.Text_4.geometry} material={materials['Rosa escuro']} />
      </group>
      <group position={[-0.64, 0.06, 1.79]} rotation={[-0.13, -0.3, 0.47]}>
        <mesh geometry={nodes.Plane019.geometry} material={materials.Luz} />
        <mesh geometry={nodes.Plane019_1.geometry} material={materials.Rosa} />
        <mesh geometry={nodes.Plane019_2.geometry} material={materials['Rosa escuro']} />
      </group>
      <group position={[0.28, -1.48, 1.3]} rotation={[-0.13, -0.3, 0.47]}>
        <mesh geometry={nodes.Cylinder_1.geometry} material={materials.Luz} />
        <mesh geometry={nodes.Cylinder_2.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Cylinder_3.geometry} material={materials['Preto.001']} />
        <mesh geometry={nodes.Cylinder_4.geometry} material={materials.Rosa} />
        <mesh geometry={nodes.Cylinder_5.geometry} material={materials['Preto escuro']} />
        <mesh geometry={nodes.Cylinder_6.geometry} material={materials['Rosa escuro']} />
        <mesh geometry={nodes.Cylinder_7.geometry} material={materials['Material.020']} />
        <mesh geometry={nodes.Cylinder_8.geometry} material={materials['Material.021']} />
        <mesh geometry={nodes.Cylinder_9.geometry} material={materials['Material.023']} />
        <mesh geometry={nodes.Cylinder_10.geometry} material={materials['Material.024']} />
        <mesh geometry={nodes.Cylinder_11.geometry} material={materials['Material.019']} />
        <mesh geometry={nodes.Cylinder_12.geometry} material={materials['Material.026']} />
      </group>
      <group position={[-0.27, -0.02, -0.12]} rotation={[-0.13, -0.3, 0.47]}>
        <mesh geometry={nodes.Cylinder001_1.geometry} material={materials.Luz} />
        <mesh geometry={nodes.Cylinder001_2.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Cylinder001_3.geometry} material={materials.Rosa} />
        <mesh geometry={nodes.Cylinder001_4.geometry} material={materials['Material.006']} />
      </group>
      <group position={[-0.21, 0.23, -0.09]} rotation={[0, -0.53, 0.52]} scale={0.64}>
        <mesh geometry={nodes.Vert_1.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Vert_2.geometry} material={materials['Material.022']} />
      </group>
    </group>
  )
}

useGLTF.preload('/hero-transformed.glb')
